/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  Overrides,
  BigNumberish,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ShuffledIdsV2, ShuffledIdsV2Interface } from "../ShuffledIdsV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "maxIds",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161018d38038061018d83398181016040528101906100329190610113565b6100647f3360bfd6d6a5176b454293daf72a17b576808b2f7ccbd3f16aa6a68f9ef74afa60001b6100d560201b60201c565b6100967ff41887b9d5a7e644ae872dc66fddaa710e231ae5c5bc5ec138bac8f8e4e9d11d60001b6100d560201b60201c565b6100c87fa8bec17963d6aa2ea18ba474c7263a40caf07a98de2a749a8d96e984ab1d523f60001b6100d560201b60201c565b8060018190555050610140565b50565b600080fd5b6000819050919050565b6100f0816100dd565b81146100fb57600080fd5b50565b60008151905061010d816100e7565b92915050565b600060208284031215610129576101286100d8565b5b6000610137848285016100fe565b91505092915050565b603f8061014e6000396000f3fe6080604052600080fdfea26469706673582212209db1bc2c6563896598c2a09ba58ff91b68e44ff00401a099af1523f719b7136764736f6c634300080c0033";

type ShuffledIdsV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ShuffledIdsV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ShuffledIdsV2__factory extends ContractFactory {
  constructor(...args: ShuffledIdsV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "ShuffledIdsV2";
  }

  deploy(
    maxIds: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ShuffledIdsV2> {
    return super.deploy(maxIds, overrides || {}) as Promise<ShuffledIdsV2>;
  }
  getDeployTransaction(
    maxIds: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(maxIds, overrides || {});
  }
  attach(address: string): ShuffledIdsV2 {
    return super.attach(address) as ShuffledIdsV2;
  }
  connect(signer: Signer): ShuffledIdsV2__factory {
    return super.connect(signer) as ShuffledIdsV2__factory;
  }
  static readonly contractName: "ShuffledIdsV2";
  public readonly contractName: "ShuffledIdsV2";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ShuffledIdsV2Interface {
    return new utils.Interface(_abi) as ShuffledIdsV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ShuffledIdsV2 {
    return new Contract(address, _abi, signerOrProvider) as ShuffledIdsV2;
  }
}
