/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ArraysToGoInterface extends utils.Interface {
  contractName: "ArraysToGo";
  functions: {
    "computeHash(string)": FunctionFragment;
    "fillArrayByName(string,uint16[])": FunctionFragment;
    "fillArrayByNameProgressively(string,uint16)": FunctionFragment;
    "getArrayByName(string)": FunctionFragment;
    "getArrayInfo(string)": FunctionFragment;
    "initialize(string,uint16)": FunctionFragment;
    "safeGetArrayByName(string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "computeHash", values: [string]): string;
  encodeFunctionData(
    functionFragment: "fillArrayByName",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fillArrayByNameProgressively",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArrayByName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getArrayInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeGetArrayByName",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillArrayByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillArrayByNameProgressively",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArrayByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArrayInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeGetArrayByName",
    data: BytesLike
  ): Result;

  events: {
    "ArrayCompleted(string,uint256)": EventFragment;
    "ArrayHashed(string,uint256,bytes32)": EventFragment;
    "ArrayInitialized(string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ArrayCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ArrayHashed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ArrayInitialized"): EventFragment;
}

export type ArrayCompletedEvent = TypedEvent<
  [string, BigNumber],
  { name: string; limit: BigNumber }
>;

export type ArrayCompletedEventFilter = TypedEventFilter<ArrayCompletedEvent>;

export type ArrayHashedEvent = TypedEvent<
  [string, BigNumber, string],
  { name: string; limit: BigNumber; hash: string }
>;

export type ArrayHashedEventFilter = TypedEventFilter<ArrayHashedEvent>;

export type ArrayInitializedEvent = TypedEvent<
  [string, BigNumber],
  { name: string; limit: BigNumber }
>;

export type ArrayInitializedEventFilter =
  TypedEventFilter<ArrayInitializedEvent>;

export interface ArraysToGo extends BaseContract {
  contractName: "ArraysToGo";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArraysToGoInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    computeHash(
      arrayName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fillArrayByName(
      arrayName: string,
      data: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fillArrayByNameProgressively(
      arrayName: string,
      numberOfElements: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<[number[]]>;

    getArrayInfo(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, boolean, string, BigNumber]>;

    initialize(
      arrayName: string,
      limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    safeGetArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<[number[]]>;
  };

  computeHash(
    arrayName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fillArrayByName(
    arrayName: string,
    data: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fillArrayByNameProgressively(
    arrayName: string,
    numberOfElements: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getArrayByName(
    arrayName: string,
    overrides?: CallOverrides
  ): Promise<number[]>;

  getArrayInfo(
    arrayName: string,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber, boolean, string, BigNumber]>;

  initialize(
    arrayName: string,
    limit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  safeGetArrayByName(
    arrayName: string,
    overrides?: CallOverrides
  ): Promise<number[]>;

  callStatic: {
    computeHash(arrayName: string, overrides?: CallOverrides): Promise<void>;

    fillArrayByName(
      arrayName: string,
      data: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    fillArrayByNameProgressively(
      arrayName: string,
      numberOfElements: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<number[]>;

    getArrayInfo(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, boolean, string, BigNumber]>;

    initialize(
      arrayName: string,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    safeGetArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<number[]>;
  };

  filters: {
    "ArrayCompleted(string,uint256)"(
      name?: string | null,
      limit?: BigNumberish | null
    ): ArrayCompletedEventFilter;
    ArrayCompleted(
      name?: string | null,
      limit?: BigNumberish | null
    ): ArrayCompletedEventFilter;

    "ArrayHashed(string,uint256,bytes32)"(
      name?: string | null,
      limit?: BigNumberish | null,
      hash?: BytesLike | null
    ): ArrayHashedEventFilter;
    ArrayHashed(
      name?: string | null,
      limit?: BigNumberish | null,
      hash?: BytesLike | null
    ): ArrayHashedEventFilter;

    "ArrayInitialized(string,uint256)"(
      name?: string | null,
      limit?: BigNumberish | null
    ): ArrayInitializedEventFilter;
    ArrayInitialized(
      name?: string | null,
      limit?: BigNumberish | null
    ): ArrayInitializedEventFilter;
  };

  estimateGas: {
    computeHash(
      arrayName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fillArrayByName(
      arrayName: string,
      data: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fillArrayByNameProgressively(
      arrayName: string,
      numberOfElements: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getArrayInfo(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      arrayName: string,
      limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    safeGetArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    computeHash(
      arrayName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fillArrayByName(
      arrayName: string,
      data: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fillArrayByNameProgressively(
      arrayName: string,
      numberOfElements: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getArrayInfo(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      arrayName: string,
      limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    safeGetArrayByName(
      arrayName: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
